I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1876, in script
    if HarukiMeeting or MeetingDenied:
  File "game/script.rpy", line 1876, in <module>
    if HarukiMeeting or MeetingDenied:
NameError: name 'MeetingDenied' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1876, in script
    if HarukiMeeting or MeetingDenied:
  File "C:\Users\njh10\Downloads\renpy-8.1.0-sdk\renpy\ast.py", line 2133, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\njh10\Downloads\renpy-8.1.0-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\njh10\Downloads\renpy-8.1.0-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1876, in <module>
    if HarukiMeeting or MeetingDenied:
NameError: name 'MeetingDenied' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.0.23051307
Epithets 3.0
Wed May 31 12:27:18 2023
